---
title: Elementi di Bioinformatica
subtitle: 8 CFU. Laurea Triennale in Informatica

url: http://elementi-bioinformatica.algolab.eu
root: http://elementi-bioinformatica.algolab.eu
author: AlgoLab

github_repository: elementi-bioinformatica
github_user: AlgoLab
github_tags_count: 2

nav:
  - name: Home
    link: "index.html"
  - name: Lezioni
    link: "lezioni.html"
  - name: Esami
    link: "esami.html"
  - name: Materiale didattico
    link: "https://github.com/AlgoLab/elementi-bioinformatica"
  - name: Codice
    link: "https://github.com/AlgoLab/elementi-bioinformatica"

simple_search: http://google.com/search
google_analytics_tracking_id: UA-32216930-1
---
